### ISSUE TITLE
some variables are not used (disk_size, disk_type, pricing_plan, replication_type)

### ISSUE THREAD

**Issue by tpoindessous** [GoogleCloudPlatform/terraform-google-sql-db#2]
Hi

thank you for your module. I noticed that some variables are not used :

- disk_size
- disk_type
- pricing_plan
- replication_type

I really care about disk_size but other people may have the need of others.

As a new year resolution, I will try to send you a pull request for these, but also for adding support for failover instance.

Thanks !

**Comment by tpoindessous** [comment]
Corrected in PR #4 

Thanks !

**Comment by danisla** [comment]
Fixed with #4
