### ISSUE TITLE
Support for private networking

### ISSUE THREAD

**Issue by thefirstofthe300** [GoogleCloudPlatform/terraform-google-sql-db#39]
Currently, attempting to use private networking errors out because a Service Networking connection and private IP is not established/created.

**Comment by namusyaka** [comment]
@thefirstofthe300 Could you provide a minimal example for reproducing the issue?

**Comment by thefirstofthe300** [comment]
I wish I had time to go about figuring that out but I've got some really tight deadlines right now. I can tell you straight away that all the resources required to do private networking as per the [Terraform resource](https://www.terraform.io/docs/providers/google/r/sql_database_instance.html#private-ip-instance) documentation don't currently exist in the module.

I did manage to jerry-rig a patch together that enables private networking that I can use: https://github.com/GoogleCloudPlatform/terraform-google-sql-db/compare/master...thefirstofthe300:ds/private-networking

I'll try to get this cleaned up and submitted as a PR but right now, I'm struggling to find time.

**Comment by mmontan** [comment]
A support for private networking is under review in https://github.com/GoogleCloudPlatform/terraform-google-sql-db/pull/35. I defined a new submodule for setting up the network, as those elements need to be created only once for all instances connected to the same VPC.

**Comment by thefirstofthe300** [comment]
I'm gonna close this since the other module was added. Any bugs that are found should be reported individually.
