### ISSUE TITLE
Standardize integration testing

### ISSUE THREAD

**Issue by aaron-lane** [GoogleCloudPlatform/terraform-google-sql-db#42]
The integration testing for this module should be standardized based on the module template. This should include obviating the need for manual steps beyond running kitchen.

**Comment by namusyaka** [comment]
I'd like to do this task after finishing upgrading terraform version to 0.12.0. Thoughts?

**Comment by kopachevsky** [comment]
@namusyaka I almost done, it PR for TF 11 version will be ready today, so you can change kitchen docker version in Makefile and verify again TF 12

By the way I have issue running kitchen converge against safer-mysql-simple test, have you stuck with following?

`       Error: Error applying plan:
       
       3 error(s) occurred:
       
       * module.safer-mysql-db.module.safer_mysql.google_sql_database.default: Resource 'google_sql_database_instance.default' not found for variable 'google_sql_database_instance.default.name'
       * module.safer-mysql-db.module.safer_mysql.random_id.user-password: Resource 'google_sql_database_instance.default' not found for variable 'google_sql_database_instance.default.name'
       * module.safer-mysql-db.module.safer_mysql.google_sql_database_instance.default: settings.0.ip_configuration.0: invalid or unknown key: private_network
`

**Comment by namusyaka** [comment]
@kopachevsky I couldn't reproduce the errors. If you can't resolve those errors, please open an issue with more details.
