### ISSUE TITLE
Name conflict when recreating failover database

### ISSUE THREAD

**Issue by wadefrancis** [GoogleCloudPlatform/terraform-google-sql-db#44]
### Scenario ###
A MySQL database restore is done on a database with an existing failover replica, requiring deletion of the failover to complete the restore. Attempting to recreate the failover database using Terraform results in a name collision error.

### Expected Behavior ###
Terraform apply should determine the replica is not present and successfully create it.

### Actual Behavior ###
Name collision error message as below:

`
	* google_sql_database_instance.failover-replica: Error, failed to create instance test-investigate-instance-failover with error code 409: googleapi: Error 409: The Cloud SQL instance already exists., instanceAlreadyExists. This may be due to a name collision - SQL instance names cannot be reused within a week.
`

### Steps to Reproduce ###
1. Using terraform, create a MySQL database with a failover replica
2. Manually restore the database which requires deletion of the failover replica.
3. Run `terraform apply` to recreate the failover replica

### Proposed Solution ###
Create a failover database name suffix that defaults to an empty string to allow the issue above to be resolved and not affect any existing code.

In `variables.tf` add the following code:
```
variable "failover_replica_name_suffix" {
  description = "An optional suffix to add to the failover database name"
  default     = ""
}
```

In 'failover_replica.tf' (line 20):
```
name                  = "${var.name}-failover${(var.failover_replica_name_suffix=="" ? "" : "-")}${var.failover_replica_name_suffix}"
```
The conditional expression in the name above gracefully handles inserting a dash before the suffix if it is provided.

The suffix can now be updated after step 2 above resulting in successful execution of `terraform apply` in step 3.

**Comment by morgante** [comment]
@namusyaka Can you take a look?

**Comment by namusyaka** [comment]
yes will do

**Comment by namusyaka** [comment]
@waderfrancis why did you try to recreate a new
failover replica by using terraform?
A failover replica should automatically recreated while failover process: https://cloud.google.com/sql/docs/mysql/high-availability?hl=en#failover-process

**Comment by wadefrancis** [comment]
@namusyaka hiya - situation was to restore a MySQL database from a backup with an existing failover replica.

It is not possible to restore a database with an attached failover replica and as such the failover must be deleted to complete the restore process.

Then attempting to recreate the failover using Terraform results in the issue described above.

The failover process is not invoked or used as part of this database restore scenario.

**Comment by namusyaka** [comment]
@wadefrancis Ah I see, I seemed misunderstanding the issue. 
The name of failover replica is determined internally, so the developer can't recreate a new failover replica.
On the other hand, I think the same issue will be happened in read replicas.

I'll fix it soon. Thanks.
