### ISSUE TITLE
Error using module.private-service-access based on the example

### ISSUE THREAD

**Issue by BastienM** [GoogleCloudPlatform/terraform-google-sql-db#45]
Hi,

In the [example](https://github.com/GoogleCloudPlatform/terraform-google-sql-db/blob/1.1.2/examples/mysql-and-postgres/main.tf#L114) for the `module.private_service_access` in v1.1.2, you are using the network's `self_link` property which results in an error : 

```sh
* google_compute_global_address.google-managed-services-range: Error creating GlobalAddress: googleapi: Error 400: Invalid value for field 'resource.name': 'google-managed-services-https://www.googleapis.com/compute/v1/projects/my-project/global/networks/main'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid
```

If I am not mistaken the [module documentation](https://github.com/GoogleCloudPlatform/terraform-google-sql-db/tree/master/modules/private_service_access) states : `vpc_network | Name of the VPC network to peer.`

So it should be :

```diff
  module "private-service-access" {
    source      = "../../modules/private_service_access"
    project_id  = "${var.project_id}"
-   vpc_network = "${google_compute_network.default.self_link}"
+   vpc_network = "${google_compute_network.default.name}"
  }
```

Once fixed, the module works as intended.

**Comment by namusyaka** [comment]
@BastienM Thanks for opening the issue.

Your fix seems good. According to [the official doc](https://www.terraform.io/docs/providers/google/r/compute_global_address.html#network), the network of google_compute_global_address should be specified as URL, but it would be [overwritten by correct link](https://github.com/terraform-providers/terraform-provider-google/blob/5ec40239f420dd6822fd5dc434b3f5b2cc0d4263/google/resource_compute_global_address.go#L389) even if passing just name.

Do you want to send a PR? If not I can fix it.

**Comment by BastienM** [comment]
No problem, I just pushed the PR.
