### ISSUE TITLE
MySQL Read Replica IP Configuration not applied

### ISSUE THREAD

**Issue by wadefrancis** [GoogleCloudPlatform/terraform-google-sql-db#49]
### Scenario
When providing read replica configuration via the variable `read_replica_ip_configuration`, the information being passed in is not used when creating the read replica. 

### Expected Behavior
Read replica should use the IP configuration from the variable `read_replica_ip_configuration`

### Actual Behavior
Read replica uses the IP configuration from the main database (via the variable `ip_configuration`)

### Steps to Reproduce
Create a master database with a read replica and supply different information in the variables `ip_configuration ` and `read_replica_ip_configuration`.

### Proposed Solution

in `read_replica.tf` update `locals`:
```
locals {
  primary_zone       = "${var.zone}"
  read_replica_zones = ["${compact(split(",", var.read_replica_zones))}"]

  zone_mapping = {
    enabled  = ["${local.read_replica_zones}"]
    disabled = "${list(local.primary_zone)}"
  }

  zones_enabled = "${length(local.read_replica_zones) > 0}"
  mod_by        = "${local.zones_enabled ? length(local.read_replica_zones) : 1}"

  zones = "${local.zone_mapping["${local.zones_enabled ? "enabled" : "disabled"}"]}"

   # ************************************************
   # Append the following:
   # ************************************************
  read_replica_ip_configuration_enabled = "${length(keys(var.read_replica_ip_configuration)) > 0 ? true : false}"
  read_replica_ip_configurations = {
    enabled  = "${var.read_replica_ip_configuration}"
    disabled = "${map()}"
  }
   # ************************************************

}
```

Then at line 38:
```
    ip_configuration            = ["${local.read_replica_ip_configurations["${local.read_replica_ip_configuration_enabled ? "enabled" : "disabled"}"]}"]
```

The same change will be required for both mysql and postgresql modules.

**Comment by namusyaka** [comment]
Definitely the bug. Seems forgetting to use those variables in each replica type.
Will fix soon

**Comment by namusyaka** [comment]
@wadefrancis I've just opened a PR for fixing the issue. could you take a look?

Btw, thanks for reporting the issue.

**Comment by wadefrancis** [comment]
@namusyaka thanks for the fix - is there a plan/timeframe to create a new tagged release with these fixes in them?

**Comment by morgante** [comment]
I have tagged v1.2.0: https://github.com/GoogleCloudPlatform/terraform-google-sql-db/releases/tag/v1.2.0
